### ISSUE TITLE
Absorb functionality to attach source tarball to finalize workflow

### ISSUE THREAD

**Issue by nwiltsie** [uclahs-cds/tool-create-release#28]
We are using [`uclahs-cds/tool-Nextflow-action/add-source-with-submodules@latest`](https://github.com/uclahs-cds/tool-Nextflow-action/tree/ae8d198ac3f0b45674078e46c8e50ba9be77871c/add-source-with-submodules) and its embedded [`uclahs-cds/tool-Nextflow-action/tar-with-submodules@latest`](https://github.com/uclahs-cds/tool-Nextflow-action/tree/ae8d198ac3f0b45674078e46c8e50ba9be77871c/tar-with-submodules) to attach source tarballs, including all submodules, to new releases.

I'd like it if we could absorb that functionality into the finalize-release workflow - all but a handful of the repositories using `add-source-with-submodules` are already using these release workflows.

An appropriate opt-in syntax for it might be changing this...

```yaml
jobs:
  finalize-release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'automation-create-release') }}
    uses: uclahs-cds/tool-create-release/.github/workflows/wf-finalize-release.yaml@v1
    secrets: inherit
    with:
      draft: false
```

... to this:

```yaml
jobs:
  finalize-release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'automation-create-release') }}
    uses: uclahs-cds/tool-create-release/.github/workflows/wf-finalize-release.yaml@v1
    secrets: inherit
    with:
      draft: false
      tar-stem: source_code_with_submodules
```
